from minHeap import minHeap
myHeap = minHeap()
myHeap.add(0)
myHeap.add(1)
myHeap.add(2)
myHeap.add(3)
myHeap.add(5)
myHeap.add(4)
myHeap.add(6)
myHeap.add(2)
myHeap.printer()
myHeap.remove(3)
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
myHeap.printer()